### ISSUE TITLE
I get AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by ndvbd** [scito/extract_otp_secret_keys#3]
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by scito** [comment]
I cannot reproduce this error.
Can you give from information? How to reproduce? Which environment? Python version? …

**Comment by stephenharris** [comment]
I had this too. Python 3.8.5. I had `protobuf-3.6.1` installed, when I upgraded to 3.14.0 it worked. (See related: https://github.com/protocolbuffers/protobuf/issues/7672)

**Comment by jmhunter** [comment]
If it helps anyone else, I had this also.

I was running this in a fresh Ubuntu 20.04 installation, and had installed the protobuf package via the distribution's packaging system (```sudo apt install python-protobuf```)

Unfortunately the version of protobuf provided is too old (3.6.1.3-2ubuntu5, to be precise) and I didn't seem to have pip installed.

I'm not a Python expert yet, and not wishing to break my new desktop installation by going down a dependency rabbit-hole, I decided to use docker as I already had that installed.

Here's my one-liner that I used to get it working, this might help others too? This presumes the input file is in ```infile```, in the current directory, where the software is also downloaded to.

```
$ cd /path/to/downloaded_script
$ docker run -it --rm --name extract_otp_secret_keys \
    -v "$PWD":/usr/src/myapp -w /usr/src/myapp \
    python:3 sh -c \
    "pip install protobuf; python extract_otp_secret_keys.py infile"
```
This will download the official Python3 docker image, install Protobuf via PIP, run the script and then exit, cleaning up after itself.

**Comment by scito** [comment]
It seems that an upgrade to protobuf 3.14.0 will solve this issue, see https://github.com/scito/extract_otp_secret_keys/issues/3#issuecomment-766436453
@ndvbd Could you fix the problem? Can I close this issue?

**Comment by harry-appinfotech** [comment]
when running examples from "tests" DIr getting error no module named "extract_otp_secrets". Pls help

**Comment by scito** [comment]
@harry-appinfotech Please provide more information, to reproduce your case, e.g. versions, working directory, commands, ...
